pull_request_rules:
  - name: automatic merge when CI passes and 2 reviews
      conditions:
        - "#approved-reviews-by>=1"
        - status-success=Android CI - Pull Request
        - base=master
      actions:
        merge:
          method: merge
